### PR TITLE
Readme acceptance

### PR DESCRIPTION
**Pull request by bradleykhan**
All hail faffew

### CODE REVIEW

**Review by richardbadman — CHANGES_REQUESTED** [review]
This will break the FE tags and categories component, please fix this as it's causing the ATs to break.

**Review by olga-brandwatch — APPROVED** [review]
🥇

**Comment by ophillipsBrandwatch** [comment]
👎

**Review by SamJamesKennedy — CHANGES_REQUESTED** [review]
Have you considered astral characters

**Review by chaicesan — APPROVED** [review]
solid work. Do merge.

**Review by SergeEgorov — APPROVED** [review]

**Comment by bw-matthew** [comment]
This PR only got 3 approvals which is less than the 4 that https://github.com/bw-matthew/i-hope-i-remember-to-make-this/pull/12 got

**Pull request closed without merging**
